#!/bin/bash
CWD="$PWD"
PPPR_ROOT="$CWD/.."
outfile=../data-generators/pkg_md5_sums
directories=( "/var/packages/" "/var/packages/builtin_files" "/var/lib/dpkg" )

source ../util/ppm-reduce-functions

outfile=$(realpath -m "$outfile")
CWD=$(realpath "$CWD")
PPPR_ROOT="$(realpath "$PPPR_ROOT")"

#    set +x
#    echo "Finished Setting Paths"
#    read -p "Press enter to continue"
 #   set -x

AWK_fn_map_deb='
/^Package:/     { sub(/^Package: /,"");  PKG=$0; }
/^Version:/     { sub(/^Version: /,"");  PKGVER=$0; }
/^Filename:/    { sub(/^Filename: /,""); PKGPATH=$0; sub(/.*\//,""); PKGFILE=$0; }


/^$/            { print PKG "|" ARCH "|" PKGVER "|" PKGFILE "|" "dpkg" "|"
                  PKG=""; PKGVER=""; PKGFILE=""; PKGPATH=""; PKGPRIO=""; PKGSECTION=""; PKGMD5="";  PKGDEP=""; }
'




#AWK_fn_DISTRO_PKGS_SPECS=

for pfx in "1" "2" "3"; do
  [ -f "$outfile"_$pfx ] && rm "$outfile"_$pfx
  touch "$outfile"
  [ -f "$outfile"_${pfx}_md5 ] && rm "$outfile"_${pfx}_md5
  touch "$outfile"_$pfx_md5
  [ -f "$outfile"_"$pfx"_db ] && rm "$outfile"_"$pfx"_db
  touch "$outfile"_"$pfx"_db
done



for a_dir in "${directories[@]}"; do
  bname="$(basename "$a_dir")"
  case "$bname" in
  packages)
    pfx=1
    cd "$a_dir"; dir_bname=$(basename "$a_dir")
    md5sum $(ls -1 *.files) "" | sed -r 's#^([^[:space:]]+)([[:space:]]+)([^[:space:]].*)([.]files)$#\3||||'$bname'|\3\4|\1'"|"'#g' | sort -t '|' -k1 >> "$outfile"_"$pfx"_md5
    
#     set +x
#    echo "Finished packages md5sums"
#    read -p "Press enter to continue"
#    set -x   
    
 #We have: filelist|, pkg, ver, pkgfile, ,pkgsdir
#We want:
#print pkg,                              arch, ver, pkgfile, dir_name, filelist, md5sum 
#android-libadb_8.1.0+r23-5|         |      |            |                |android-libadb_8.1.0+r23-5.files|3d2a36e9e638b22d68014aef5ad52283packages


#AWK_FN_pkgs='{
#  filelist=$1; pkg=$2; ver=$3; pkgfile=$4; arch=""; info_dir_alias=$6; md5sum=$7; md5sum=""
#  libboost-thread1.71.0_1.71.0.files|750b3f445d293035c92ee016955c47fa|packages
#}'     



AWK_fn_prepend_file_list='BEGIN {FS = "|"}
{  
	pkg=$1; arch=""; ver=$2; 
	pkgfile=$3
	 db_list=$3
	 pkgfile_noExt=$3
	sub(/\.[^.]+$/, "", pkgfile_noExt)
	filelist=pkgfile_noExt "." ext
	md5sum=""
    print pkgfile_noExt "|" arch "|" ver "|" pkgfile "|" db_dir "|" filelist "|" md5sum "|" pkg}
'	
    cut -f2,3,8 -d'|' --output-delimiter="|" "$a_dir"/user-installed-packages | \
      awk -v ext=files -v db_dir=$bname "$AWK_fn_prepend_file_list" | sort -t '|' -k1 >> "$outfile"_"$pfx"_db #f1=file_list_name, f2=pkg, f3=version, f4=pkg_file, f5=packages

     #set +x
    #echo "Finished packages db"
    #read -p "Press enter to continue"
    #set -x   



    #join -t "|" -j1 "$outfile"_"$pfx"_db "$outfile"_"$pfx"_md5 | sort -t '|' -k1 >> "$outfile"_$pfx
    #set +x
    "$PPPR_ROOT"/bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true \
        "$PPPR_ROOT"/dpkg_mappers/identity.awk "$PPPR_ROOT"/core/identity.awk \
        <(cat "${outfile}"_"$pfx"_md5 $outfile"_"$pfx"_db") > "$outfile"_${pfx}_map_shuffle    
    
    "$PPPR_ROOT"/bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true \
        "$PPPR_ROOT"/dpkg_mappers/identity.awk "$PPPR_ROOT"/dpkg_reducers/PKGS_reducer.awk \
        <(cat "${outfile}"_"$pfx"_md5 $outfile"_"$pfx"_db") > "$outfile"_${pfx}
        
      set +x
    echo "Finished packages"
    read -p "Press enter to continue"
    set -x          
        
    #cat "$outfile"_$pfx | awk "$AWK_FN_pkgs" > "$outfile"_${pfx}_awk
    #set +x
    #echo "Finished:
    #"$PPPR_ROOT"/bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true \
        #"$PPPR_ROOT"/dpkg_mappers/identity.awk "$PPPR_ROOT"/dpkg_reducers/PKGS_reducer.awk \
        #<(cat "${outfile}"_"$pfx"_md5 $outfile"_"$pfx"_db") > "$outfile"_${pfx}
     #"    
    #read -p "Press enter to continue"
    #set -x
    
    #set +x
    #read -p "Press enter to continue"
    #set -x
    ;;
  builtin_files)
    pfx=2
    cat /var/packages/DISTRO_PKGS_SPECS | \
      "$CWD"/distro_pkgs_specs__to__compat_pkg.awk | sort -k2 -t '|' > ${outfile}"_distro_pkgs_specs" #f1=pkg_name, f2=distro_pkgs_specs_name
    cd "$a_dir"; dir_bname=$(basename "$a_dir")
    md5sum $(ls -1f) "" | sed -r 's#^([^[:space:]]+)([[:space:]]+)([^[:space:]].*)$#\3|\1|'"$bname"'#g' | \
      sort -t '|' -k1 >> "${outfile}"_"$pfx"_md5 #f1=pkg_name, f2=distro_pkgs_specs_nam


      
    join -t "|" -1 1 -2 2 "${outfile}"_"$pfx"_md5 ${outfile}"_distro_pkgs_specs" | sort -t '|' -k4 > "${outfile}"_specs_and_md5
    #./bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true \
    #    ./dpkg_mappers/identity.awk ./dpkg_reducers/PKGS_reducer.awk \
    #    <(cat "${outfile}"_"$pfx"_md5 ${outfile}"_distro_pkgs_specs")
    #PKGS_reducer.awk  
#    cut -f2,3,8 -d'|' --output-delimiter="|" "$a_dir"/../woof-installed-packages | \
#      awk -v ext=files -v db_dir=builtin_compat_files "$AWK_fn_prepend_file_list" | sort -t '|' -k1 >> "${outfile}"_"$pfx"_db

    cut -f2,3,8 -d'|' --output-delimiter="|" "$a_dir"/../woof-installed-packages | \
      sort -t '|' -k2 >> "${outfile}"_"$pfx"_db     
      
    join -t "|" -1 4 -2 2 "${outfile}"_specs_and_md5 "${outfile}"_"$pfx"_db | sort -t '|' -k4 | uniq -u > "${outfile}"_${pfx}_pre
 
    
    
    
    #awk "$AWK_FN_builtin" |
    
 AWK_FN_builtin='
 BEGIN {FS="|"}
 {
  filelist=""; fistbuiltin=$1; pkg=$2; arch=""; info_dir_alias=$6; md5sum=$3; dir_name=$4; ver=$6; pkgfile=$7
  print pkg "|" arch "|" ver "|" pkgfile "|" dir_name "|" filelist "|" md5sum
}'     
    
    cat "${outfile}"_${pfx}_pre | awk "$AWK_FN_builtin" | sort  -t '|' -k1 >> "${outfile}"_${pfx}
    
    ;;       
  dpkg)
    pfx=3
    cd "$a_dir/info"; dir_bname=$(basename "$a_dir")
    md5sum $(ls -1 *.list; ls -1 *.md5sums) "" \
       | sed -r 's#^([^[:space:]]+)([[:space:]]+)([^[:space:]]+.*)([.])([^.]*)$#\3||dpkg|\3\4|\1|'"$bname"'#g' \
       | sed -r 's#([^:]+)(:?[^\|]*\|)(.*)#\1|||||\2\3#g' \
       | sort > "${outfile}"_"$pfx"_md5 #f1=pkg, f2=:arch, f3=ver, f4=pkgfile, f5=dir_name, f6=filelist, f7=md5sum
    cd ..
    cat status | awk -v db_dir=dpkg "$AWK_fn_map_deb" > "${outfile}"_"$pfx"_db
    cd $CWD/..
    cat "${outfile}"_"$pfx"_md5  "${outfile}"_"$pfx"_db > "${outfile}"_"$pfx"_data
    cd $CWD/..
    
    #Output: pkg, arch, ver, pkgfile, dir_name, filelist, md5sum
    ./bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true ./dpkg_mappers/identity.awk ./dpkg_reducers/LB_reducer.awk "${outfile}"_"$pfx"_data > "${outfile}"_"$pfx"
    #./bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true ./dpkg_mappers/identity.awk ./core/identity.awk "${outfile}"_"$pfx"_data > "${outfile}"_"$pfx"
    #./bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true ./core/identity.awk ./dpkg_reducers/LB_reducer.awk "${outfile}"_"$pfx"_data > "${outfile}"_"$pfx"
    #./bash-reduce -v shuffle_OFS="@@@@" -v shuffle_FS="|" -v Keep_Key=true ./dpkg_mappers/LB_Mapper.awk ./dpkg_reducers/LB_reducer.awk "${outfile}"_"$pfx"_data > "${outfile}"_"$pfx"
    #./bash-reduce -v shuffle_OFS="'@@@@'" -v shuffle_FS="|" -v Keep_Key=true ./dpkg_mappers/LB_Mapper.awk ./core/shuffle.awk "${outfile}"_"$pfx"_data > "${outfile}"_"$pfx"
    #join -t "|" -j 1 "${outfile}"_"$pfx"_db "${out_file}"_specs_and_md5 >> "${outfile}"_$pfx
    ;;      
  esac
done #
#cd $CWD
cat cat "${outfile}"_1 "$outfile"_2 "$outfile"_3 "${outfile}"_"$pfx"_db  | sort -t '|' -k1 > "${outfile}"_data

#cd $CWD/..
#./bash-reduce ./dpkg_mappers/LB_Mapper ./dpkg_reducers/LB_reducer "${outfile}"_data >> "${outfile}"_$pfx
